# =========================
# ? Server Configuration
# =========================
server.port=8080

# =========================
# ? Database Configuration
# =========================
spring.datasource.url=jdbc:mysql://mysql-dissertation-fraud-detection-project-scalable-services-as.b.aivencloud.com:11181/fraud_detection_db?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_VgnsJwz8pZ0baXSbjgy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



# =========================
# ? Logging (Optional)
# =========================
logging.level.org.springframework.security=DEBUG



# -----------------------------
# KAFKA CONFIGURATION
# -----------------------------
spring.kafka.bootstrap-servers=localhost:9092
kafka.transaction.topic=transaction-notifications
kafka.transaction.producerAck=all
kafka.transaction.batchSize=16384
kafka.transaction.lingerMs=1
kafka.transaction.maxRequestSize=1048576
kafka.transaction.bufferMemory=33554432
kafka.transaction.maxBlockMs=60000
kafka.transaction.compression_type=snappy
kafka.transaction.requests_per_connection=5
kafka.transaction.max_age_ms=300000
kafka.transaction.max_idle_ms=540000

# -----------------------------
# SPRING MAIL CONFIGURATION
# -----------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

